[[p7zip]]
arch = "aarch64"
git-tree-sha1 = "f242f37180f22c755ce2607cec9274f362bec948"
os = "macos"

    [[p7zip.download]]
    sha256 = "78c0128983f18e991b389d7c817ad79674d676c0f4d74d495758953d1d159959"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.2+0/p7zip.v17.8.2.aarch64-apple-darwin.tar.gz"
[[p7zip]]
arch = "aarch64"
git-tree-sha1 = "42180b4915587afae8e9d5d9bc14c85241a90851"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "77f22c4b3e1b872cde816f94ebfe43357ef38b1e6a873dc442bd657dba7ccd3d"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.2+0/p7zip.v17.8.2.aarch64-linux-gnu.tar.gz"
[[p7zip]]
arch = "aarch64"
git-tree-sha1 = "93e01d3138070499b3b010b3e39a39034e41c12d"
libc = "musl"
os = "linux"

    [[p7zip.download]]
    sha256 = "07c1d1a1561dcf43278fefeee22497e4e4626b614bcd86d5fec1cda663a1f5eb"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.2+0/p7zip.v17.8.2.aarch64-linux-musl.tar.gz"
[[p7zip]]
arch = "aarch64"
git-tree-sha1 = "f461632975be42e6e9a0e85abed4e10a6b8f959a"
os = "freebsd"

    [[p7zip.download]]
    sha256 = "eb546b17f2e886c16fe27c73e9da72d99752ee2ec5f2d1ee3adeb756392003d2"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.2+0/p7zip.v17.8.2.aarch64-unknown-freebsd.tar.gz"
[[p7zip]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0043af35e0846e8c9b65a7f334e0934acc2295e3"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "2b8597e7105eeb2b46c9113de6698985ac29a489f3600de07d6ae7c3192cb0cd"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.2+0/p7zip.v17.8.2.armv6l-linux-gnueabihf.tar.gz"
[[p7zip]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "24e92b4168f85a4b8840fa2fc27b9a50ee6d6fb1"
libc = "musl"
os = "linux"

    [[p7zip.download]]
    sha256 = "167c35677c61d27b2067651c6f89f349af4a5c48cdb70b70648b394cf7f0a92b"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.2+0/p7zip.v17.8.2.armv6l-linux-musleabihf.tar.gz"
[[p7zip]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cd8ec3e4f9682f700f074a4e4825773211825405"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "d5409f63c136a1a30c426daf6fad5525cf9714a986d699b2713d90994fb758b2"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.2+0/p7zip.v17.8.2.armv7l-linux-gnueabihf.tar.gz"
[[p7zip]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7f71fd410364b4e96f255c749a548e1e1485707f"
libc = "musl"
os = "linux"

    [[p7zip.download]]
    sha256 = "ad010f4dce5dd7ff9880fd9b511a1154b54929eaccac29fa0ca58f2261f8fc4f"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.2+0/p7zip.v17.8.2.armv7l-linux-musleabihf.tar.gz"
[[p7zip]]
arch = "i686"
git-tree-sha1 = "9f4f56927ab71cdb77ad9978a3bede1c864d6ed1"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "be8b37a0cf64faabfef9ca4d7abc5f14fbb4ac3c7170d661968c2d3070a3f703"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.2+0/p7zip.v17.8.2.i686-linux-gnu.tar.gz"
[[p7zip]]
arch = "i686"
git-tree-sha1 = "7b30f0ebc0af8f8e1b045fad6759cb897149aa4d"
libc = "musl"
os = "linux"

    [[p7zip.download]]
    sha256 = "540b6cb3c6a57c9e4fc4c8ff1d23ba8157e9c10d96b851b6c2cb64cfd389558a"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.2+0/p7zip.v17.8.2.i686-linux-musl.tar.gz"
[[p7zip]]
arch = "i686"
git-tree-sha1 = "6dc3bf1d5c952fe2cd9f0c0552af969052c32b7a"
os = "windows"

    [[p7zip.download]]
    sha256 = "c07412570469bc61c064f704db6656786b709ae029071cea8d7a191ee8f71bb2"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.2+0/p7zip.v17.8.2.i686-w64-mingw32.tar.gz"
[[p7zip]]
arch = "powerpc64le"
git-tree-sha1 = "306a2b5933e776f93bf682b6fbab3b366febd5e7"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "8eb0f42a484992b26d16f511f17b926afb1a276afeb930ffe39dafdef8a7e4f3"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.2+0/p7zip.v17.8.2.powerpc64le-linux-gnu.tar.gz"
[[p7zip]]
arch = "riscv64"
git-tree-sha1 = "3837ae056244c885933fbaa97a0706c5f9558fb5"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "44c1f8d360bca6892a3e7f80c894e2da83b6b46f1e054a11ec15eee85eadb3ac"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.2+0/p7zip.v17.8.2.riscv64-linux-gnu.tar.gz"
[[p7zip]]
arch = "x86_64"
git-tree-sha1 = "7145123675d6d59ef52d51c0e4e044541b3437f7"
os = "macos"

    [[p7zip.download]]
    sha256 = "dca4dc688e9c561a1b0d9dbee5a217a0aa00388c94c3dad5264fee4e1d6415b4"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.2+0/p7zip.v17.8.2.x86_64-apple-darwin.tar.gz"
[[p7zip]]
arch = "x86_64"
git-tree-sha1 = "96fbeeb6261e2d7972a70d3b48e0da2e9244808b"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "5c9c1d0f3bd79141fc383f269ad09fc7b2251f757c21322961c2c772751c3b75"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.2+0/p7zip.v17.8.2.x86_64-linux-gnu.tar.gz"
[[p7zip]]
arch = "x86_64"
git-tree-sha1 = "0238c76123c0a0dd27154acd56c62fe7fc31c0a6"
libc = "musl"
os = "linux"

    [[p7zip.download]]
    sha256 = "30304fd4f6a882efa817ce23c8b2826ba938344b0fcda7885b7551cd1e13d5f7"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.2+0/p7zip.v17.8.2.x86_64-linux-musl.tar.gz"
[[p7zip]]
arch = "x86_64"
git-tree-sha1 = "09c4afbd21a4cbbe75cbb5c24a5c3e557bdceaf2"
os = "freebsd"

    [[p7zip.download]]
    sha256 = "b1b46f8b4bfa840f8f1a74db7a195cd83f1a16141c91a2cc3452ddb8181a4dd0"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.2+0/p7zip.v17.8.2.x86_64-unknown-freebsd.tar.gz"
[[p7zip]]
arch = "x86_64"
git-tree-sha1 = "e4726c82658b83d9964e2db57ab9f06f4a359c1b"
os = "windows"

    [[p7zip.download]]
    sha256 = "1e1da43219fec124cf68bb606a0d932ab8d194cce820db3b8a4e4acfa162d9dc"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.2+0/p7zip.v17.8.2.x86_64-w64-mingw32.tar.gz"
