[[p7zip]]
arch = "aarch64"
git-tree-sha1 = "45d1235155f060b6bb3c6b2a48e2349b6fad1845"
os = "macos"

    [[p7zip.download]]
    sha256 = "16c9ac2c52d05a7a7a891a410cd83fc5dce41a1685c3d228411075782de54909"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.1+0/p7zip.v17.8.1.aarch64-apple-darwin.tar.gz"
[[p7zip]]
arch = "aarch64"
git-tree-sha1 = "5388b8a949155cd06c36caeb267fb1a53dc8dfe8"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "cae9367ecb7bc4a477866f76b354c791f8a255644b3acb6ee3d5c01c8f49221e"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.1+0/p7zip.v17.8.1.aarch64-linux-gnu.tar.gz"
[[p7zip]]
arch = "aarch64"
git-tree-sha1 = "ae83cea99abb94ad5f76e682195d7eb896a64c85"
libc = "musl"
os = "linux"

    [[p7zip.download]]
    sha256 = "66e1b4d9cdd70b51164ac2311e18850b93c340c9c63525bae3f3aa4e3482c420"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.1+0/p7zip.v17.8.1.aarch64-linux-musl.tar.gz"
[[p7zip]]
arch = "aarch64"
git-tree-sha1 = "477d95312b3b82e1ab09842744ee6d3e63fe96df"
os = "freebsd"

    [[p7zip.download]]
    sha256 = "f2ad4407420f68de7d15435190ef85e0f147ffd575f6d6ed5001e7bc15df8568"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.1+0/p7zip.v17.8.1.aarch64-unknown-freebsd.tar.gz"
[[p7zip]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "72dbe69fbe8b9f73e812cd389795ca9026a225ce"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "0f022a5f00dae432a44a4cf88507c30b642ba9695f5c5e3c99c34e5e09b884e5"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.1+0/p7zip.v17.8.1.armv6l-linux-gnueabihf.tar.gz"
[[p7zip]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5adb210aa2d0e835f142477508bd5ab13ad2adfa"
libc = "musl"
os = "linux"

    [[p7zip.download]]
    sha256 = "e91e0a5cead8c86baf72f663293440c7b28773703cb9d713560876d3e5bf28c2"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.1+0/p7zip.v17.8.1.armv6l-linux-musleabihf.tar.gz"
[[p7zip]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8634dabbcfc0d299e85f35a4cb6b9459a8f00bac"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "29a3c75b7960ca9c1af1b66bdbcc49725bd91fbf16ba3885bca2f40e9b248e66"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.1+0/p7zip.v17.8.1.armv7l-linux-gnueabihf.tar.gz"
[[p7zip]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "729346e9dea492d5700c9def875865b5d1f7bfe1"
libc = "musl"
os = "linux"

    [[p7zip.download]]
    sha256 = "d7979b989f6df2737e57d290dbaccf0b9870790cb98f99762ca801302cd35640"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.1+0/p7zip.v17.8.1.armv7l-linux-musleabihf.tar.gz"
[[p7zip]]
arch = "i686"
git-tree-sha1 = "35e3737145e6170ac91a17662e43b1700da94d22"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "215fe3ad8a9830a7565d36c12593523092202d6a2a4b3a1dbf310b4a481388ba"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.1+0/p7zip.v17.8.1.i686-linux-gnu.tar.gz"
[[p7zip]]
arch = "i686"
git-tree-sha1 = "afa893dbe94622d1ce51c91a8399249fe801fccb"
libc = "musl"
os = "linux"

    [[p7zip.download]]
    sha256 = "4407b966b31ce456885aadf9377dada57116e94338f12c943e0348492d2b0d80"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.1+0/p7zip.v17.8.1.i686-linux-musl.tar.gz"
[[p7zip]]
arch = "i686"
git-tree-sha1 = "094b68f6b831bcc01e9405a61c79203e59c3d887"
os = "windows"

    [[p7zip.download]]
    sha256 = "2309af24d5e4e5729b4dccc49656ba0dd9b56091a71bbb4d490b8c5f24fcc166"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.1+0/p7zip.v17.8.1.i686-w64-mingw32.tar.gz"
[[p7zip]]
arch = "powerpc64le"
git-tree-sha1 = "805015a9a4cf8251b60809058e0af52e1f569479"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "b66754a5ef3d5f843a79676b02237b4a975ec3aa7ee70a5716665514c5bf2d3c"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.1+0/p7zip.v17.8.1.powerpc64le-linux-gnu.tar.gz"
[[p7zip]]
arch = "riscv64"
git-tree-sha1 = "f77a90fcc1a12d7a59b094194371a139cc64c62e"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "ec77ff8d8e1cb3b93e6f7a0d864f391d7c4fbb9919c80d1a944e54b4c688c08f"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.1+0/p7zip.v17.8.1.riscv64-linux-gnu.tar.gz"
[[p7zip]]
arch = "x86_64"
git-tree-sha1 = "46a5918406ebd0114dc8bad8d30f7bfe5320873e"
os = "macos"

    [[p7zip.download]]
    sha256 = "31fbac2084afb097b868cae8d930f8d9c03b8f0dfbdb6dd953d0cfece740366a"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.1+0/p7zip.v17.8.1.x86_64-apple-darwin.tar.gz"
[[p7zip]]
arch = "x86_64"
git-tree-sha1 = "fd961e3746b23ee76e7fac7a0995e7ac67b6bd99"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "7803590328120254b661ed4ded2749e2ebd285de8db0fd26224de3b21083f058"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.1+0/p7zip.v17.8.1.x86_64-linux-gnu.tar.gz"
[[p7zip]]
arch = "x86_64"
git-tree-sha1 = "2b7be0a8dd044ed3b60796664d251576ce813447"
libc = "musl"
os = "linux"

    [[p7zip.download]]
    sha256 = "08434bb544883c14ff02793758a42db2abd9caf868dcd546524379c7d665ca50"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.1+0/p7zip.v17.8.1.x86_64-linux-musl.tar.gz"
[[p7zip]]
arch = "x86_64"
git-tree-sha1 = "4812b7a37eddf7d693006302b49f8c63de3aaecf"
os = "freebsd"

    [[p7zip.download]]
    sha256 = "49c80c4a1c80013695e9c2a7bc6ca0c8171f9d62914622b04bf3d627fe014a80"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.1+0/p7zip.v17.8.1.x86_64-unknown-freebsd.tar.gz"
[[p7zip]]
arch = "x86_64"
git-tree-sha1 = "edac7e4fd466096acb79fbd0eaf6b2eb905a01dc"
os = "windows"

    [[p7zip.download]]
    sha256 = "126008aaf5e06314f38f124bed9cfe7955078fdcf7d9abadbe9d11487e09a037"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.1+0/p7zip.v17.8.1.x86_64-w64-mingw32.tar.gz"
