[[p7zip]]
arch = "aarch64"
git-tree-sha1 = "cac2cf4242676705e85c3a62fe1699f5af82a13f"
os = "macos"

    [[p7zip.download]]
    sha256 = "b366fa49b012dc354da6dbf157d176cc6a31818ab65d6eaf236a86faab97157a"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.0+0/p7zip.v17.8.0.aarch64-apple-darwin.tar.gz"
[[p7zip]]
arch = "aarch64"
git-tree-sha1 = "a072e677db421d515442c974b23fb031e396bcab"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "e0040da51ef000cc6f0479a7e2e9141e4de43fe4aa0cf631a8fd0eed691072ac"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.0+0/p7zip.v17.8.0.aarch64-linux-gnu.tar.gz"
[[p7zip]]
arch = "aarch64"
git-tree-sha1 = "acab128d9e8942c30b17b5d09da7371e15567298"
libc = "musl"
os = "linux"

    [[p7zip.download]]
    sha256 = "13d4d62de6462d1725dffaf20425f88e8d14ba183e093d8dee1a0bbc78c8c761"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.0+0/p7zip.v17.8.0.aarch64-linux-musl.tar.gz"
[[p7zip]]
arch = "aarch64"
git-tree-sha1 = "de50b83a92478f3895c1465be64f5a8721acc83c"
os = "freebsd"

    [[p7zip.download]]
    sha256 = "0c4e1880b41da72cdebe227c0367c29967be359af13b3ffec5a17ff4b3d604b6"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.0+0/p7zip.v17.8.0.aarch64-unknown-freebsd.tar.gz"
[[p7zip]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a45bf8afe3dba591de94ee587c8b712d153f4418"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "1b387c2f0c44e38dc94ebc27f5fa8f63a8fc1c6660a9b8b8a38bff19d28a3e13"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.0+0/p7zip.v17.8.0.armv6l-linux-gnueabihf.tar.gz"
[[p7zip]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1cb00e0815cc0f8061e287673aa737b641dabbfc"
libc = "musl"
os = "linux"

    [[p7zip.download]]
    sha256 = "60e350f3fa0042d3ae0def42573faa46ecd274e3d4f4ed074fa5255a2be26b19"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.0+0/p7zip.v17.8.0.armv6l-linux-musleabihf.tar.gz"
[[p7zip]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d0736b882a2bd40a29d17cc63945cc4663321428"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "60120be862078cd41bb45c44ace42362a8486bd0c73e62f92801f972043c00ec"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.0+0/p7zip.v17.8.0.armv7l-linux-gnueabihf.tar.gz"
[[p7zip]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3384399e5a9c11804152859b9e84c652ef23dac7"
libc = "musl"
os = "linux"

    [[p7zip.download]]
    sha256 = "fc5c4689f616aa3fd6692be7e6fec28a06bbc4ce56e29a61f1e72b6712396e67"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.0+0/p7zip.v17.8.0.armv7l-linux-musleabihf.tar.gz"
[[p7zip]]
arch = "i686"
git-tree-sha1 = "b964d18d45d80a9faf579c7cddef42185ed8fc55"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "32ceb861cfd2f9e402bd57da3dfa316a71e18ecbd831d3223d54f0f16e3b4b8b"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.0+0/p7zip.v17.8.0.i686-linux-gnu.tar.gz"
[[p7zip]]
arch = "i686"
git-tree-sha1 = "ed2ff788a23cbc02a7379db2dedd10679b04d1ae"
libc = "musl"
os = "linux"

    [[p7zip.download]]
    sha256 = "0929a393ca4a657337dab73093091f749d309b2b30000c56ee3fbc57a513ef2b"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.0+0/p7zip.v17.8.0.i686-linux-musl.tar.gz"
[[p7zip]]
arch = "i686"
git-tree-sha1 = "95acf7e5cb6b8ede801d508ad0d99173dc2d3670"
os = "windows"

    [[p7zip.download]]
    sha256 = "8394aa0c24119d49dd0581b635282d3dc45a6d7f4dc571a61843cd8cf7f1b343"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.0+0/p7zip.v17.8.0.i686-w64-mingw32.tar.gz"
[[p7zip]]
arch = "powerpc64le"
git-tree-sha1 = "f0c7fea619741b023cf8937bc5e8bd2c352fb272"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "81743a928f39f2dae3d4bf6853286d1fdfe4257cbff658758a746a6c7d8a6278"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.0+0/p7zip.v17.8.0.powerpc64le-linux-gnu.tar.gz"
[[p7zip]]
arch = "riscv64"
git-tree-sha1 = "390b2c7f352186104245f4384cd067ec03bf5692"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "9d9ad025f2725382360dd701d9a19f60da2ac09bf863abc27de3dfff193e9206"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.0+0/p7zip.v17.8.0.riscv64-linux-gnu.tar.gz"
[[p7zip]]
arch = "x86_64"
git-tree-sha1 = "96b552cf7ff63cb6cbffb5cdf8bf85be2e7493da"
os = "macos"

    [[p7zip.download]]
    sha256 = "5c97281fa01a4e13220ecb97dde4d2c0f334d2be59d5d111a239e6965af264d2"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.0+0/p7zip.v17.8.0.x86_64-apple-darwin.tar.gz"
[[p7zip]]
arch = "x86_64"
git-tree-sha1 = "de35adb33e5e18b7d6625658760384aeab043c6a"
libc = "glibc"
os = "linux"

    [[p7zip.download]]
    sha256 = "620c128625ad0ef16b2dabbb04842fc3207b906e1353033093ff9fda55b1ce71"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.0+0/p7zip.v17.8.0.x86_64-linux-gnu.tar.gz"
[[p7zip]]
arch = "x86_64"
git-tree-sha1 = "2ce38b93389816339509c591f63b11b83b9c2263"
libc = "musl"
os = "linux"

    [[p7zip.download]]
    sha256 = "d911446f77f6780d54fb14d631fd95066d07d3a97e8ef119bfbfdf511924e261"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.0+0/p7zip.v17.8.0.x86_64-linux-musl.tar.gz"
[[p7zip]]
arch = "x86_64"
git-tree-sha1 = "e4e67e2feb6580724a537cc0613ea43a25ee0704"
os = "freebsd"

    [[p7zip.download]]
    sha256 = "6761b21409a2f8bc24e2f623730a7805a140597e467635c929ae462c2c59c5fe"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.0+0/p7zip.v17.8.0.x86_64-unknown-freebsd.tar.gz"
[[p7zip]]
arch = "x86_64"
git-tree-sha1 = "eb1a6837ab0d60d1b4061f7b68011ecf3e005b3d"
os = "windows"

    [[p7zip.download]]
    sha256 = "0642d5d767d22bf42fdfeb1a8048a95d73c374c55a92d853fc8558a6e5c1e3b3"
    url = "https://github.com/JuliaBinaryWrappers/p7zip_jll.jl/releases/download/p7zip-v17.8.0+0/p7zip.v17.8.0.x86_64-w64-mingw32.tar.gz"
